name: CI Pipeline

on:
  push:
    branches: [ "Development" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build --build-arg ENV_FILE=./.env -t tinzarpaing/lumiere_backend .
      working-directory: C:\Paing\Langara_3\4980-Project2\Lumiere_BackEnd
    - name: Push to Dockerhub
      run: docker push tinzarpaing/lumiere_backend