name: Docker Image CI

on:
  push:
    branches: [ "Development" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t Lumiere_BackEnd .
    - name: Push to Dockerhub
      run: docker push tpaing00/Lumiere_BackEnd:latest
  
